### ISSUE TITLE
Plugins should throw meaningful error if included in wrong build phase

### ISSUE THREAD

**Issue by topfunky** [quirkey/jim#13]
By trial and error I discovered that the 'macro' plugin only works if it's in a "before_push.rb" hook.

Plugins should have a way to specify which phase of the build process they should be included in. Otherwise, people will see a weird error that doesn't help to pinpoint the problem.

**Comment by quirkey** [comment]
This is actually a ticket for quirkey/soca and should be fixed in the latest version.
