### ISSUE TITLE
Add "closure-compiler" gem to dependencies.

### ISSUE THREAD

**Issue by jimeh** [quirkey/jim#3]

**Comment by jimeh** [comment]
Hmm, I just noticed that this is mentioned in the readme, so probably this is a defunct issue.

**Comment by quirkey** [comment]
I added more explicit warnings for when using compile and the compressor gem cant be found. I dont want to actually add it as a dependency since it requires Java and is only actually required for the compress() step and not for the other jim commands.

Thanks!
